### ISSUE TITLE
侧边栏无法隐藏&播放页面的部分按钮无响应

### ISSUE THREAD

**Issue by zhongfly** [gozaoo/BlurLyric2.0#10]
以下均是试用demo（https://blurlyric.app/ ）后遇到的问题

1.点击侧边栏任意一项后会展开侧边栏，但不会自动隐藏，甚至无法手动隐藏（至少我没有找到相关的操作提示）。
这使得界面的部分内容被遮挡
![image](https://user-images.githubusercontent.com/11155705/206891475-b71ec924-5891-4ce0-984f-5f8e0b693719.png)

2.播放页面，点击“设置选项”的图标无响应
控制台报错：
![image](https://user-images.githubusercontent.com/11155705/206891586-6c12277d-8df9-4927-a6bf-333dff907f44.png)

3.循环模式缺少提示，且模式较少
点击循环模式可以切换，但缺少提示告诉用户切换成了什么模式
姑且猜测目前可供选择的模式有列表循环和随机播放2种，希望添加单曲循环模式

**Comment by g2nnyS** [comment]
第一项BUG我们没有成功复现，根据设计应该是点击图钉标志后展开侧边栏，再次点击图钉后收起。没有遇到点击其他按钮后会展开侧边栏的情况。(在手机端和桌面端，和基于electron的桌面端均没有复现该BUG，可以再详细描述一下复现BUG的细节吗？)
播放界面的设置选项我们暂时没有开发，将来可能会加入音量调节/音质调节的选项
另外循环模式的问题，默认为列表循环模式，点击一次后切换至单曲循环模式，再点击一次为随机播放，再次点击会回到列表循环模式。确实缺少了明显的提示，未来会改进

**Comment by zhongfly** [comment]
原来是点击图钉来隐藏吗…我确实没见过这样的
我现在再次使用也的确没有出现“点击任意图标都会展开”的情况
我觉得那图钉处的描述文字可以是“隐藏描述”或者“收起侧边栏”这样的，说明点击后可以隐藏。
图钉这一图标也不是很贴切，应该换成某种暗示可以展开的图标，如>

**Comment by gozaoo** [comment]
问题3，这个按钮确实缺少反馈，仅仅是单纯的图标变换。可以考虑加个气泡在按钮上方显示一下当前是什么模式或您是否有比较优的反馈方案，期待您的意见！
