### ISSUE TITLE
登录BUG

### ISSUE THREAD

**Issue by qinfengge** [gozaoo/BlurLyric2.0#24]
![image](https://github.com/Project-And-Factory/BlurLyric/assets/35164697/ec85bdd4-41b7-47d3-8226-feb9c4a9d546)
死循环了，已经获取到user了啊

**Comment by qinfengge** [comment]
Windows最新版本，控制台已经打印出cookie了。但是一直在循环下面2个方法🤔

**Comment by g2nnyS** [comment]
这bug，难顶。。。

**Comment by iamPorter** [comment]
这bug是两三四个月前就有在汇报的问题罢，就gozaoo感觉自己用没毛病所以一直不修😳

不过私人FM什么的倒是可以顺着网易云API的Cookies用（毕竟只是GUI的问题嘛，看看别人[YesPlayMusic](https://github.com/qier222/YesPlayMusic)就知道）

不过看Releases，gozaoo有在两周前修过……没修好？

**Comment by g2nnyS** [comment]
> 这bug是两三四个月前就有在汇报的问题罢，就gozaoo感觉自己用没毛病所以一直不修😳
> 
> 不过私人FM什么的倒是可以顺着网易云API的Cookies用（毕竟只是GUI的问题嘛，看看别人[YesPlayMusic](https://github.com/qier222/YesPlayMusic)就知道）

笑死，我也跟他说了无数次了，他跟我说他那边无法复现。
前两周的复现他发现是页面刷新的问题，但是修了之后他没问题了，我也没法子

**Comment by qinfengge** [comment]
另外一个建议，是否考虑使用Tauri代替电子垃圾Electron

**Comment by g2nnyS** [comment]
> 另外一个建议，是否考虑使用Tauri代替电子垃圾Electron

看情况，可以试试。electron确实臃肿
但是我们没人会rust

**Comment by gozaoo** [comment]
已尝试降级要求的tokenversion了，请更新最新版本重试

**Comment by gozaoo** [comment]
若仍有问题请联系我们

**Comment by g2nnyS** [comment]
![image](https://github.com/Project-And-Factory/BlurLyric/assets/72686586/bef0d88f-b969-440a-8508-53936c5bfd66)
登录已修（至少我这里没啥问题了），到Actions内下新的构建版本。完全没问题了我再发个新的Releases

如果没啥疑问的话，我就先关掉这个issue了

**Comment by iamPorter** [comment]
咱就是说，这老问题是照例的没修好 
现象也是照例的反复请求status
@g2nnyS 要不你重开一下Issue？

**Comment by g2nnyS** [comment]
> 

不可能啊，看看你的tokenversion

**Comment by g2nnyS** [comment]
> 咱就是说，这老问题是照例的没修好 现象也是照例的反复请求status @g2nnyS 要不你重开一下Issue？

你二狗给tokenversion改回去了😅

**Comment by g2nnyS** [comment]
改回去了
