### ISSUE TITLE
在测试中暴露出的一些BUG

### ISSUE THREAD

**Issue by g2nnyS** [gozaoo/BlurLyric2.0#27]
## bug ##

1.在切换歌曲时，有概率会出现音量调节（播放界面的更多设置中）失效的情况。

复现步骤：切歌然后玄学触发
补充材料：暂无

2.在Ubuntu下,登录无法加载出二维码。

复现步骤：在Ubuntu环境下使用构建软件包安装后打开，点击扫码登录，无法加载二维码并且控制台报错。
补充材料：
![image](https://github.com/Project-And-Factory/BlurLyric/assets/72686586/8b913c35-024f-40bd-ac80-1ed1ab6978cb)
![image](https://github.com/Project-And-Factory/BlurLyric/assets/72686586/72f3b470-ef24-46c2-b1b0-2e59e1251ffe)

**Comment by iamPorter** [comment]
第一个问题，有两个猜想你们可以看看是不是：

* 最近API请求音频的速度似乎变慢了？有没有可能是因为请求不到音频然后崩了？
* 解灰时切换到UnblockNetEaseMusic上时出的故障？

但我毕竟没经历过（第二种猜想里找到一首灰色的歌曲也不太容易），有机会的话可以试试看

**Comment by g2nnyS** [comment]
> 第一个问题，有两个猜想你们可以看看是不是：
> 
> * 最近API请求音频的速度似乎变慢了？有没有可能是因为请求不到音频然后崩了？
> * 解灰时切换到UnblockNetEaseMusic上时出的故障？
> 
> 但我毕竟没经历过（第二种猜想里找到一首灰色的歌曲也不太容易），有机会的话可以试试看

确实，在今天下午的测试中请求音频的速度明显慢了。还会出现明明获取不到其它音源的音频（但此时网易云是有音源的）还会切换到解灰音源并卡住不播放，只能手动切到网易云音源（出现问题的歌曲是《火影忍者疾风传》OP3的歌曲《ブルーバード》可能是因为网易云的音源只有30s试听所以切到了网易云音源）

但我觉得这个情况貌似和获取不到登录二维码以及音量调节失效关系不大，获取不到登录二维码貌似是一个函数在Ubuntu的环境下无法执行（我不知道什么原因）

**Comment by gozaoo** [comment]
请提供Ubuntu环境中在控制台中的网络（network）中，链接‘..../login/qr/key’中的返回数据
