### ISSUE TITLE
Macos Blurlyric 打不开

### ISSUE THREAD

**Issue by dajgduyqwgdq** [gozaoo/BlurLyric2.0#29]
<img width="263" alt="Screenshot 2023-05-28 at 6 19 20 PM" src="https://github.com/Project-And-Factory/BlurLyric/assets/134359851/d696eaa1-371f-4420-9b48-64cf3be33813">

**Comment by g2nnyS** [comment]
到系统偏好设置界面，进入安全性与隐私，点击左下角锁头解锁更改后将软件设置成任何来源。

随后打开Mac终端，输入
`sudo chmod -R 777 BlurLyric的路径`（可以直接把软件拖进终端窗口，会自动获取路径）

输入密码授权后即可打开
