### ISSUE TITLE
下载音乐的命名与后缀问题

### ISSUE THREAD

**Issue by iamPorter** [gozaoo/BlurLyric2.0#32]
![image](https://github.com/Project-And-Factory/BlurLyric/assets/103353940/4b9ef6fd-7661-41cd-a008-a7f0bb615c8e)
![image](https://github.com/Project-And-Factory/BlurLyric/assets/103353940/6a4c2a43-64ac-433a-a1c2-394bcd835569)
![image](https://github.com/Project-And-Factory/BlurLyric/assets/103353940/bd537455-e18d-413a-ba5c-d58f253a6b9e)

1. 文件下载不会给音乐命名，统一起名``mp3.mp3``，后续手动写入音乐名需要手动码字，而某些字符不是键盘能直接输入的。
2. 上述两个音乐下载下来的时候，网易云API都是请求到无损/Hi-Res音质的，文件编码应该都是FLAC，但程序根据惯例把下载的文件统一命名成了``mp3.mp3``。

**预希望的两种解决方式**
- 在blob下载的时候把名字写进去；或使用剪切板把文件名写入，在“另存为”的时候就可以直接粘贴
- 通过下载链接或文件码率快速判断文件后缀（如320Kbps及以下判定MP3，320Kbps以上判定FLAC）

> *另注：*
> *就“文件码率”计算，程序对FLAC文件的演算似乎和Windows右击菜单“属性”的有不一样的地方？有一个文件，BlurLyric显示2000K，Windows却显示只有1500Kbps*

**Comment by gozaoo** [comment]
请更新最新版本

**Comment by gozaoo** [comment]
另外，就“文件码率”计算问题，文件码率非Blurlyric计算，Blurlyric显示的码率来源于api提供的音频码率，与实际计算上有偏差。
