### ISSUE TITLE
macOS 13 版本启动无画面

### ISSUE THREAD

**Issue by dajgduyqwgdq** [gozaoo/BlurLyric2.0#33]
窗口里面什么都没有纯白
<img width="1440" alt="Screenshot 2023-07-07 at 8 06 16 PM" src="https://github.com/Project-And-Factory/BlurLyric/assets/134359851/2bafa86d-05ac-4728-97f0-063366cec978">

**Comment by g2nnyS** [comment]
复现了问题，发现只是窗口是白的，但浏览器访问本地18775端口是没问题的。我看看咋回事

**Comment by g2nnyS** [comment]
禁用硬件加速试试看

**Comment by dajgduyqwgdq** [comment]
我使用的是M2好像没有硬件加速

**Comment by NobodyHere-rrr** [comment]
13.3, V2.4.0, M1
启动后直接崩溃

https://paste.ubuntu.com/p/VpGYfdmGJB/plain/

**Comment by gozaoo** [comment]
已检查到可能存在导致无法启动的原因并修复，已经在dev分支上上传了最新的版本，请在 https://github.com/Project-And-Factory/BlurLyric/actions/workflows/node.js.yml 处下载最新构建

**Comment by gozaoo** [comment]
本issues将不再处理，我们将在3.0版本上修复此问题
