### ISSUE TITLE
使用npm安装完成后打开，一直卡在加载用户数据中不动，等了很久也没有变化

### ISSUE THREAD

**Issue by Kenny-Ch** [gozaoo/BlurLyric2.0#8]
![image](https://user-images.githubusercontent.com/54130213/201513802-d7cdcf7e-faa8-4d75-9c42-861cd8df67bf.png)

**Comment by Kenny-Ch** [comment]
终端运行可以看到报错
![image](https://user-images.githubusercontent.com/54130213/201513929-f0f56e83-ad86-4e71-a5ff-ef042dae959f.png)

**Comment by g2nnyS** [comment]
开发环境出现了疏漏

请将 `BlurLyric目录/src/network/request.js`中
的值 `api:'/'`
改为`api:'/api/'`

**Comment by Kenny-Ch** [comment]
> 开发环境出现了疏漏
> 
> 请将 `BlurLyric目录/src/network/request.js`中 的值 `api:'/'` 改为`api:'/api/'`

下载了最新的代码，还是没有找到`api:'/api/'`
如下图所示：
![image](https://user-images.githubusercontent.com/54130213/201570614-4d5d6d91-f217-408e-8c5e-cb8d21292cc8.png)
另外，使用最新的代码运行报错，如图：
![image](https://user-images.githubusercontent.com/54130213/201570686-ae6e1b4f-73b0-46e7-a38c-f4132ec1953c.png)

**Comment by g2nnyS** [comment]
您应访问18776端口，18775是API端口，通过18776的/api目录反代
如果还是不行，我回家之后看看是怎么回事

**Comment by gozaoo** [comment]
上述问题我会在新版本修复，请更新您的仓库安装依赖后
双击 `启动.bat`
或者 `npm run test`
