### ISSUE TITLE
服务器运行出现这个错误提示

### ISSUE THREAD

**Issue by bigbubu233** [gozaoo/BlurLyric2.0#9]
![QQ截图20221114004828](https://user-images.githubusercontent.com/67695317/201533636-4ccbfcc9-4d2d-4c22-b6e7-db9c0ac0006a.png)
 不懂这个是什么情况

**Comment by g2nnyS** [comment]
可以尝试重新拉取仓库内容，并删除yarn.lock

**Comment by gozaoo** [comment]
运行前请先安装依赖
命令行输入
`npm install`
再双击 运行.bat即可

**Comment by gozaoo** [comment]
推荐您下载最新版仓库再使用哦
